<script>
import { store } from '../store.js';

export default {
  data() {
    return {
      store,
      availableFlagIcons: [
        'xx',
        'ad',
        'ae',
        'af',
        'ag',
        'ai',
        'al',
        'am',
        'ao',
        'aq',
        'ar',
        'as',
        'at',
        'au',
        'aw',
        'ax',
        'az',
        'ba',
        'bb',
        'bd',
        'be',
        'bf',
        'bg',
        'bh',
        'bi',
        'bj',
        'bl',
        'bm',
        'bn',
        'bo',
        'bq',
        'br',
        'bs',
        'bt',
        'bv',
        'bw',
        'by',
        'bz',
        'ca',
        'cc',
        'cd',
        'cf',
        'cg',
        'ch',
        'ci',
        'ck',
        'cl',
        'cm',
        'cn',
        'co',
        'cr',
        'cu',
        'cv',
        'cw',
        'cx',
        'cy',
        'cz',
        'de',
        'dj',
        'dk',
        'dm',
        'do',
        'dz',
        'ec',
        'ee',
        'eg',
        'eh',
        'er',
        'es',
        'et',
        'fi',
        'fj',
        'fk',
        'fm',
        'fo',
        'fr',
        'ga',
        'en',
        'gd',
        'ge',
        'gf',
        'gg',
        'gh',
        'gi',
        'gl',
        'gm',
        'gn',
        'gp',
        'gq',
        'gr',
        'gs',
        'gt',
        'gu',
        'gw',
        'gy',
        'hk',
        'hm',
        'hn',
        'hr',
        'ht',
        'hu',
        'id',
        'ie',
        'il',
        'im',
        'in',
        'io',
        'iq',
        'ir',
        'is',
        'it',
        'je',
        'jm',
        'jo',
        'jp',
        'ke',
        'kg',
        'kh',
        'ki',
        'km',
        'kn',
        'kp',
        'kr',
        'kw',
        'ky',
        'kz',
        'la',
        'lb',
        'lc',
        'li',
        'lk',
        'lr',
        'ls',
        'lt',
        'lu',
        'lv',
        'ly',
        'ma',
        'mc',
        'md',
        'me',
        'mf',
        'mg',
        'mh',
        'mk',
        'ml',
        'mm',
        'mn',
        'mo',
        'mp',
        'mq',
        'mr',
        'ms',
        'mt',
        'mu',
        'mv',
        'mw',
        'mx',
        'my',
        'mz',
        'na',
        'nc',
        'ne',
        'nf',
        'ng',
        'ni',
        'nl',
        'no',
        'np',
        'nr',
        'nu',
        'nz',
        'om',
        'pa',
        'pe',
        'pf',
        'pg',
        'ph',
        'pk',
        'pl',
        'pm',
        'pn',
        'pr',
        'ps',
        'pt',
        'pw',
        'py',
        'qa',
        're',
        'ro',
        'rs',
        'ru',
        'rw',
        'sa',
        'sb',
        'sc',
        'sd',
        'se',
        'sg',
        'sh',
        'si',
        'sj',
        'sk',
        'sl',
        'sm',
        'sn',
        'so',
        'sr',
        'ss',
        'st',
        'sv',
        'sx',
        'sy',
        'sz',
        'tc',
        'td',
        'tf',
        'tg',
        'th',
        'tj',
        'tk',
        'tl',
        'tm',
        'tn',
        'to',
        'tr',
        'tt',
        'tv',
        'tw',
        'tz',
        'ua',
        'ug',
        'um',
        'us',
        'uy',
        'uz',
        'va',
        'vc',
        've',
        'vg',
        'vi',
        'vn',
        'vu',
        'wf',
        'ws',
        'ye',
        'yt',
        'za',
        'zm',
        'zw',
        'arab',
        'cefta',
        'cp',
        'dg',
        'eac',
        'es-ct',
        'es-ga',
        'es-pv',
        'eu',
        'gb-eng',
        'gb-nir',
        'gb-sct',
        'gb-wls',
        'ic',
        'pc',
        'sh-ac',
        'shhl',
        'sh-ta',
        'un',
        'xk',
      ],
    }
  },
  methods: {
  },
  props: {
    userStatus: {
      type: Boolean,
      required: true,
    }
  }
}
</script>

<template>
  <main>
    <div class="container-lg mt-4 pt-1">
      <div class="row row-gap-5">
        <!-- Col with a card -->
        <div class="col-4" v-if="this.userStatus" v-for="film in store.filmsCorrespondances">
          <div class="card h-100" style="width: 18rem;">
            <div class="card-header">
              {{ film.title }}
            </div>
            <ul class="list-group list-group-flush">
              <li class="list-group-item">
                <span>Original title:</span>
                {{ film.original_title }}
              </li>
              <li class="list-group-item">
                <span>Original language: </span>
                <span class="fi" :class="[`fi-${film.original_language}`]">{{ availableFlagIcons.includes(film.original_language) ? '' : film.original_language }}</span>
              </li>
              <li class="list-group-item">
                <span>Vote:</span> 
                {{ film.vote_average }}</li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </main>
</template>

<style lang="scss" scoped>
  .card-header {
    font-size: 1.2rem;
    font-weight: 700;
  }

  .card ul span:not(.fi) {
    filter: invert(0.3);
  }
  
</style>